static const struct canon_usb_cmdstruct canon_usb_cmd[] =
        {
                { CANON_USB_FUNCTION_GET_FILE, "Get file", 0x01, 0x11, 0x202,
                        0x40 },
                { CANON_USB_FUNCTION_MKDIR, "Make directory", 0x05, 0x11, 0x201,
                        0x54 },
                { CANON_USB_FUNCTION_RMDIR, "Remove directory", 0x06, 0x11,
                        0x201, 0x54 },
                { CANON_USB_FUNCTION_DISK_INFO, "Disk info request", 0x09, 0x11,
                        0x201, 0x5c },
                /* 0x0a is overloaded: "flash device ident" and "delete file",
                 * with different responses */
                { CANON_USB_FUNCTION_FLASH_DEVICE_IDENT, "Flash device ident",
                        0x0a, 0x11, 0x202, 0x40 },
                { CANON_USB_FUNCTION_DELETE_FILE_2, "Delete file", 0x0a, 0x11,
                        0x201, 0x54 },
                { CANON_USB_FUNCTION_GET_DIRENT, "Get directory entries", 0x0b,
                        0x11, 0x202, 0x40 },
                /* Command code 0x0d is overloaded: delete file (old),
                 * disk info request ID (new). */
                { CANON_USB_FUNCTION_DELETE_FILE, "Delete file", 0x0d, 0x11,
                        0x201, 0x54 },
                { CANON_USB_FUNCTION_DISK_INFO_2, "Disk info request (new)",
                        0x0d, 0x11, 0x201, 0x5c },
                /* Command code 0x0e is overloaded: set file attribute (old),
                 * flash device ID (new). And the response is different: fixed
                 * length in old, variable length in new. */
                { CANON_USB_FUNCTION_SET_ATTR, "Set file attributes", 0x0e,
                        0x11, 0x201, 0x54 },
                { CANON_USB_FUNCTION_FLASH_DEVICE_IDENT_2,
                        "Flash device ident (new)", 0x0e, 0x11, 0x202, 0x40 },
                { CANON_USB_FUNCTION_SET_FILE_TIME, "Set file time", 0x0f, 0x11,
                        0x201, 0x54 },

                { CANON_USB_FUNCTION_IDENTIFY_CAMERA, "Identify camera", 0x01,
                        0x12, 0x201, 0x9c },
                { CANON_USB_FUNCTION_GET_TIME, "Get time", 0x03, 0x12, 0x201,
                        0x60 },
                { CANON_USB_FUNCTION_SET_TIME, "Set time", 0x04, 0x12, 0x201,
                        0x54 },
                /* 0x05 is overloaded: "change owner" and "get owner", with
                 * different responses */
                { CANON_USB_FUNCTION_CAMERA_CHOWN, "Change camera owner", 0x05,
                        0x12, 0x201, 0x54 },
                { CANON_USB_FUNCTION_GET_OWNER, "Get owner name (new)", 0x05,
                        0x12, 0x201, 0x74 },
                { CANON_USB_FUNCTION_CAMERA_CHOWN_2, "Change owner (new)", 0x06,
                        0x12, 0x201, 0x54 },
                { CANON_USB_FUNCTION_POWER_STATUS, "Power supply status", 0x0a,
                        0x12, 0x201, 0x58 },
                /* 0x13 is overloaded: remote camera control in the original
                 protocol, power status in the new protocol. */
                { CANON_USB_FUNCTION_CONTROL_CAMERA, "Remote camera control",
                        0x13, 0x12, 0x201, 0x40 },
                { CANON_USB_FUNCTION_POWER_STATUS_2,
                        "Power supply status (new)", 0x13, 0x12, 0x201, 0x58 },
                { CANON_USB_FUNCTION_RETRIEVE_CAPTURE,
                        "Download a captured image", 0x17, 0x12, 0x202, 0x40 },
                { CANON_USB_FUNCTION_RETRIEVE_PREVIEW,
                        "Download a captured preview", 0x18, 0x12, 0x202, 0x40 },
                { CANON_USB_FUNCTION_UNKNOWN_FUNCTION, "Unknown function", 0x1a,
                        0x12, 0x201, 0x80 },
                { CANON_USB_FUNCTION_EOS_LOCK_KEYS, "EOS lock keys", 0x1b, 0x12,
                        0x201, 0x54 },
                { CANON_USB_FUNCTION_EOS_UNLOCK_KEYS, "EOS unlock keys", 0x1c,
                        0x12, 0x201, 0x54 },
                { CANON_USB_FUNCTION_EOS_GET_BODY_ID, "EOS get body ID", 0x1d,
                        0x12, 0x201, 0x58 },
                { CANON_USB_FUNCTION_GET_PIC_ABILITIES, "Get picture abilities",
                        0x1f, 0x12, 0x201, 0x384 },
                { CANON_USB_FUNCTION_GENERIC_LOCK_KEYS,
                        "Lock keys and turn off LCD", 0x20, 0x12, 0x201, 0x54 },
                { CANON_USB_FUNCTION_20D_UNKNOWN_1, "Unknown EOS 20D function",
                        0x21, 0x12, 0x201, 0x54 },
                { CANON_USB_FUNCTION_20D_UNKNOWN_2, "Unknown EOS 20D function",
                        0x22, 0x12, 0x201, 0x54 },
                { CANON_USB_FUNCTION_EOS_GET_BODY_ID_2, "Get body ID (new)",
                        0x23, 0x12, 0x201, 0x58 },
                { CANON_USB_FUNCTION_GET_PIC_ABILITIES_2,
                        "Get picture abilities (new)", 0x24, 0x12, 0x201, 0x474 },
                { CANON_USB_FUNCTION_CONTROL_CAMERA_2,
                        "Remote camera control (new)", 0x25, 0x12, 0x201, 0x40 },
                { CANON_USB_FUNCTION_RETRIEVE_CAPTURE_2,
                        "Download captured image (new)", 0x26, 0x12, 0x202, 0x40 },
                { CANON_USB_FUNCTION_LOCK_KEYS_2, "Lock keys (new)", 0x35, 0x12,
                        0x201, 0x5c }, { CANON_USB_FUNCTION_UNLOCK_KEYS_2,
                        "Unlock keys (new)", 0x36, 0x12, 0x201, 0x54 },
                /* WARNING: I don't think this is really the right value, but
                 * it gives no error on EOS 20D -- swestin 22-Mar-05 */
                { CANON_USB_FUNCTION_SET_ATTR_2, "Set file attributes (new))",
                        0x07, 0x11, 0x201, 0x54 }, { 0, NULL, 0, 0, 0, 0 } };

